---
# Load datas

# set AD datas ==================================================================================================

- name: ACL INSIDE AD
  hosts: dc
  roles:
  - { role: 'windows_domain/acl', tags: 'acl'}
  vars:
    ad_acls: "{{lab.domains[lab.hosts[dict_key].domain].acls | default({})}}"
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.domains[domain].domain_password}}"