---
- name: DCS AD DATA CONFIGURATION
  hosts: dc
#  hosts: dc03
  roles:
    - { role: 'windows_domain/password_policy', tags: 'policy', try_before_lock: "5", pass_length: "5", lock_duration: "00:05:00", lock_observation: "00:05:00", complexity: false}
# CREATE OBJECTS
    - { role: 'windows_domain/user_group_ou_computer/ou',       tags: 'ad_domain_data', objects: "{{domain_ous}}",        action: "create" }
    - { role: 'windows_domain/user_group_ou_computer/group',    tags: 'ad_domain_data', objects: "{{domain_groups}}",     action: "create" }
    - { role: 'windows_domain/user_group_ou_computer/user',     tags: 'ad_domain_data', objects: "{{domain_users}}",      action: "create" }
    - { role: 'windows_domain/user_group_ou_computer/computer', tags: 'ad_domain_data', objects: "{{domain_computers}}",  action: "create" }
    - { role: 'windows_domain/gmsa/gmsa',                       tags: 'ad_domain_data', objects: "{{domain_gmsa}}",       action: "create" }
# ADD kerberos ressource based constrained delegations
    - { role: 'windows_domain/gmsa/gmsa',                       tags: 'ad_domain_data', objects: "{{domain_gmsa}}",       action: "add_delegates"}
    - { role: 'windows_domain/user_group_ou_computer/user',     tags: 'ad_domain_data', objects: "{{domain_users}}",      action: "add_delegates" }
    - { role: 'windows_domain/user_group_ou_computer/computer', tags: 'ad_domain_data', objects: "{{domain_computers}}",  action: "add_delegates" }
    - { role: 'windows_domain/user_group_ou_computer/group',    tags: 'ad_domain_data', objects: "{{domain_groups}}",     action: "add_members" }
# ADD kerberos unconstained and constrained delegations
    - { role: 'windows_domain/kerberos_delegation',             tags: 'ad_domain_data', objects: "{{domain_service_accounts}}"}
    - { role: 'windows_domain/kerberos_delegation',             tags: 'ad_domain_data', objects: "{{domain_gmsa}}"}
    - { role: 'windows_domain/kerberos_delegation',             tags: 'ad_domain_data', objects: "{{domain_computers}}"}
# AD Account Control
    - { role: 'windows_domain/ad_account_control',              tags: 'ad_domain_data', objects: "{{domain_gmsa}}"}
    - { role: 'windows_domain/ad_account_control',              tags: 'ad_domain_data', objects: "{{domain_users}}"}
    - { role: 'windows_domain/ad_account_control',              tags: 'ad_domain_data', objects: "{{domain_computers}}"}
