---
- name: DCS AD DATA CONFIGURATION
  hosts: dc03
  roles:
    - { role: 'windows_domain/password_policy', tags: 'policy', try_before_lock: "5", pass_length: "5", lock_duration: "00:05:00", lock_observation: "00:05:00", complexity: false}
    - { role: 'windows_domain/user_group_ou_computer/group', tags: 'ad_domain_data', action: "create" }
    - { role: 'windows_domain/user_group_ou_computer/user', tags: 'ad_domain_data' }
    - { role: 'windows_domain/user_group_ou_computer/computer', tags: 'ad_domain_data' }
    - { role: 'windows_domain/user_group_ou_computer/group', tags: 'ad_domain_data', action: "add_members" }
  vars:
    ad_users: "{{domain_users}}"
    ad_groups: "{{domain_groups}}"
    ad_computers: "{{domain_computers}}"
