---
# doesen't work see : https://github.com/ansible-collections/community.windows/blob/main/plugins/modules/win_domain_group_membership.ps1
# ligne 62 : use the given credentials to distant domain -> wrong
- name: CROSS DOMAIN GROUPS
  hosts: dc
  roles:
  - { role: 'windows_domain/groups_domains', tags: 'groups_domains'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_server: "{{lab.hosts[dict_key].hostname}}.{{domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.domains[domain].domain_password}}"
    domain_groups_members: "{{lab.domains[domain].multi_domain_groups_member | default({}) }}"
