---
- name: ADCS INSTALL
  hosts: adcs
  roles:
    - { role: 'windows_domain/adcs/adcs', tags: 'adcs'}
    - { role: 'windows_domain/adcs/templates', tags: 'adcs_templates', when: cert_templates is defined and cert_templates|length > 0}
    - { role: 'windows_domain/adcs/acl_templates', tags: 'adcs_templates', when: acls_adcs_templates   | length >0, acls: "{{acls_adcs_templates}}"}
    - { role: 'windows_domain/adcs/acl_authority', tags: 'adcs_templates', when: acls_adcs_authority   | length >0, acls: "{{acls_adcs_authority}}", CAName: "{{ca_common_name}}"}