---
# Load datas
#- name: disable
#  hosts: srv01
#  roles:
#    - { role: 'windows_settings/manage_net_adapter' , action: "disable"}
#
#- name: enable
#  hosts: srv01
#  roles:
#    - { role: 'windows_settings/manage_net_adapter' , action: "enable", adapter: "{{nat_adapter}}"}

- name: "SETUP LOCAL SECURITIES"
#  hosts: all
  hosts: srv01
  tasks:
    - include_role:
        name: "windows_settings/{{item.key}}"
      vars:
        params : "{{ item.value | default({}) }}"
        domain: "{{lab.hosts[dict_key].domain}}"
        domain_username: "{{domain}}\\Administrator"
        domain_password: "{{lab.domains[domain].domain_password}}"
      with_dict: "{{local_security | default({}) }}"


