---
# Load datas

# set AD datas ==================================================================================================

- name: AD ACL
  hosts: dc
  roles:
  - { role: 'windows_domain/acl', tags: 'acl'}
  vars:
    ad_acls: "{{acls | default({})}}"
    
- name: ADCS ACL
  hosts: adcs
  roles:
    - { role: 'windows_domain/adcs/acl_templates', tags: 'adcs_templates', when: acls_adcs_templates   | length >0, acls: "{{acls_adcs_templates}}"}
    - { role: 'windows_domain/adcs/acl_authority', tags: 'adcs_templates', when: acls_adcs_authority   | length >0, acls: "{{acls_adcs_authority}}", CAName: "{{ca_common_name}}"}


- name: SET LAPS USERS AND GROUPS PERMISSION
  hosts: dc
  roles:
    - { role: 'windows_domain/laps/permissions', tags: 'laps-permissions', when: laps_path  | length > 0}

