---
- name: CONFIGURE LAPS ON DCS
  hosts: dc
  roles:
    - { role: 'windows_domain/laps/dc', tags: 'laps-dc'}

- name: CONFIGURE LAPS ON SERVERS
  hosts: domain_server,  domain_workstation
  roles:
    - { role: 'windows_domain/laps/server', tags: 'laps-server'}



- name: VERIFY AND SHOW LAPS PASSWORDS
  hosts: dc
  roles:
    - { role: 'windows_domain/laps/verify', tags: 'laps-verify'}
  vars:
    hosts_dict: "{{hostvars}}"

- name: SET LAPS USERS AND GROUPS PERMISSION
  hosts: dc
  roles:
    - { role: 'windows_domain/laps/permissions', tags: 'laps-permissions'}

