---
# Load datas
- name: "INSTALL MSSQL EXPRESS"
  hosts: mssql
  max_fail_percentage: 0
  tasks:
    - name: print some vars
      debug:
        msg: 
          - "SQLSVCACCOUNT_NAME: {{mssql_svcaccount| default('NT AUTHORITY\\NETWORK SERVICE')}}"
          - "SQLSVCACCOUNT: {{mssql_svcaccount| default('NT AUTHORITY\\NETWORK SERVICE')}}"
          - "SQLSVCPASSWORD: {{hostvars[domain_dc_ansible_inventory_key].domain_users[mssql_svcaccount].password| default('')}}"
          - "sql_sysadmins: {{ssql_sysadmins | default([]) }}"
          - "executeaslogin: {{mssql_executeaslogin  | default({}) }}"
          - "executeasuser:  {{mssql_executeasuser | default({}) }}"
          - "sa_password: {{mssql_sa_password}}"
          - "linked_servers: {{mssql_linked_servers | default({}) }}"

#    - name: print some vars
#      fail:
#        msg: "stop" 


- name: "INSTALL MSSQL EXPRESS"
  hosts: mssql
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain/mssql/mssql', tags: 'mssql'}
#    - { role: 'windows_domain/mssql/mssql_link', tags: 'mssql, mssql_link'}
  vars:
    SQLSVCACCOUNT: "{{domain_name}}\\{{mssql_svcaccount}}"
    SQLSVCPASSWORD: "{{hostvars[domain_dc_ansible_inventory_key].domain_users[mssql_svcaccount].password}}"
    SQLYSADMIN: "{{SQLSVCACCOUNT}}"
    sql_sysadmins: "mssql_sysadmins | default([]) }}"
    executeaslogin: "{{mssql_executeaslogin  | default({}) }}"
    executeasuser:  "{{mssql_executeasuser | default({}) }}"
    sa_password: "{{mssql_sa_password}}"
    linked_servers: "{{mssql_linked_servers | default({}) }}"

- name: "INSTALL SQL SERVER MANAGEMENT STUDIO"
  hosts: mssql_ssms
  roles:
    - { role: 'windows_domain/mssql/mssql_ssms', tags: 'mssql_ssms'}
