---
- name: "INSTALL USER DATA ON MEMBERS"
  hosts: domain_server, domain_workstation
  tasks:
#    - include_role: 
#        name: "windows_domain/install_softwares"
#      vars:
#        softwares: "{{packages}}"
    - include_role:
        name: "windows_domain/clone_repos"
      vars:
        repositories: "{{u.value}}"
        user: "{{u.key}}"
        net_bios: "{{domain_netbios_name}}"
        password: "{{hostvars[domain_dc_ansible_inventory_key].domain_users_regular[u.key].password}}"
      loop: "{{ user_repos|dict2items }}"
      loop_control:
        loop_var: u
    - include_role:
        name: "windows_domain/download_files"
      vars:
        downloads: "{{u.value}}"
        user: "{{u.key}}"
        net_bios: "{{domain_netbios_name}}"
        password: "{{hostvars[domain_dc_ansible_inventory_key].domain_users_regular[u.key].password}}"
      loop: "{{ user_downloads|dict2items }}"
      loop_control:
        loop_var: u

#- name: remove vagrant domain account
#  hosts: dc
#  roles:
#    - { role: 'windows_domain/remove_vagrant', tags: 'remove_vagrant'}
#- name: remove vagrant local account
#  hosts: domain
#  roles:
#    - { role: 'windows_settings/remove_vagrant', tags: 'remove_vagrant'}
