---
#- name: "Adjust DNS Server"
#  hosts: dc
#  roles:
#    - { role: 'windows_domain/dns_listening', tags: 'server'}

- name: "JOIN SERVERS TO DOMAIN"
  hosts: domain_server
  roles:
    - { role: 'windows_domain/member_server', tags: 'server'}

- name: "JOIN WORKSTATIONS TO DOMAIN"
  hosts: domain_workstation
  roles:
    - { role: 'windows_domain/member_workstation', tags: 'workstation'}
