---

#- name: DCS AD DATA CONFIGURATION
#  hosts: dc
#  max_fail_percentage: 0
#  roles:
#    - { role: 'windows_domain/user_group_ou_computer/group',    tags: 'ad_domain_data', objects: "{{domain_groups}}",     action: "add_members" }

- name: DCS AD DATA CONFIGURATION
  hosts: mssql
  max_fail_percentage: 0
  tasks:
    - name: Restart service
      win_service:
        name: 'MSSQL${{ mssql_instance_name }}'
        force_dependent_services: yes
        state: restarted
      register: status_mssql

    - debug:
        var: status_mssql