Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    # pass through specific device based on identifying it
    libvirt.usb :vendor => '0x1234', :product => '0xabcd'
    # pass through a host device where multiple of the same vendor/product exist
    libvirt.usb :bus => '1', :device => '1'
  end
end

        v.customize ["setextradata", :id, "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled", "1"] # Disable Host Time Sync
        v.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
        v.customize ["modifyvm", :id, "--vram", "128"]
        v.customize ["modifyvm", :id, "--usb", "on"]
        v.customize ["modifyvm", :id, "--usbehci", "on"] # usb2
        v.customize ["modifyvm", :id, "--usbxhci", "on"] # usb3
        v.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'EDUP AX3000 (mt7921u)', '--active', 'yes', '--vendorid', '0x0e8d', '--productid', '0x7961']
        v.customize ['usbfilter', 'add', '1', '--target', :id, '--name', 'Alfa AWUS036ACHM (mt76x0u)', '--active', 'yes', '--vendorid', '0x0e8d', '--productid', '0x7610']
        v.customize ['usbfilter', 'add', '2', '--target', :id, '--name', 'RTL8153 Gigabit Ethernet Adapter', '--serialnumber', '001000001', '--active', 'yes', '--vendorid', '0x0bda', '--productid', '0x8153']
 

