galaxy_info:
  role_name: yubikey
  author: jubeaz
  description: configure yubikey
  license: GPL-2.0-or-later
  min_ansible_version: 2.1
  platforms:
    - name: Archlinux
      versions:
        - all
  galaxy_tags: []
dependencies: []
