---
- name: Configure Proxy Daemon
  block:
    - name: Create libvirtd config file
      template:
        src: templates/libvirtd/libvirtd.conf.j2
        dest: /etc/libvirt/libvirtd.conf
        owner: root
        group: root
        mode: 0644

    - name: Create virtproxyd systemd files
      template:
        src: "templates/libvirtd/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: 0644
      loop:  "{{ _libvirt_systemd_files.libvirtd }}"
  notify: restart libvirtd
  when: deployment_type != 'modular'

- name: Configure Proxy Daemon
  block:
    - name: Create virtproxyd config file
      template:
        src: templates/virtproxyd/virtproxyd.conf.j2
        dest: /etc/libvirt/virtproxyd.conf
        owner: root
        group: root
        mode: 0644

    - name: Create virtproxyd systemd files
      template:
        src: "templates/virtproxyd/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: 0644
      loop:  "{{ _libvirt_systemd_files.virtproxyd }}"
  notify: restart virtproxyd
  when: deployment_type == 'modular'
     
- name: Configure Logging Daemon
  block:
    - name: Create virtlogd config file
      template:
        src: templates/virtlogd/virtlogd.conf.j2
        dest: /etc/libvirt/virtlogd.conf
        owner: root
        group: root
        mode: 0644

    - name: Create virtlogd systemd files
      template:
        src: "templates/virtlogd/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: 0644
      loop:  "{{ _libvirt_systemd_files.virtlogd }}"
  notify: restart virtlogd
    
    
- name: Configure Locking Daemon
  block:
    - name: Create virtlockd config file
      template:
        src: templates/virtlockd/virtlockd.conf.j2
        dest: /etc/libvirt/virtlockd.conf
        owner: root
        group: root
        mode: 0644

    - name: Create virtlockd systemd files
      template:
        src: "templates/virtlockd/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: 0644
      loop:  "{{ _libvirt_systemd_files.virtlockd }}"
  notify: restart virtlockd

- include_tasks: config_driver.yml
  loop: "{{ _libvirt_systemd_files.drivers |dict2items }}"
  loop_control:
    loop_var: __libvirt_driver
  when: deployment_type == 'modular'
