- name: Create {{ pool.name }} pool dir
  file:
    path: "{{ pool.path }}"
    state: directory
    owner: root
    group: "{{ _libvirt_group }}"
    mode: 0775

- name: Create {{ pool.name }} pool
  virt_pool:
    command: define
    name: "{{ pool.name }}"
    xml: '{{ lookup("template", "templates/dir_pool.xml.j2") }}'

- name: Get {{ pool.name }} pool status
  virt_pool:
    command: status
    name: "{{ pool.name }}"
  register: __pool_status

- name: Start {{ pool.name }} pool
  virt_pool:
    command: create
    name: "{{ pool.name }}"
  when:  __pool_status.status != "active"
 
- name: AutoStart {{ pool.name }} pool
  virt_pool:
    autostart: yes
    name: "{{ pool.name }}"
