---
- include_tasks: variables.yml
- include_tasks: asserts.yml
- name: assert proper distribution
  assert:
    that:
      - ansible_distribution in ['Archlinux', 'Ubuntu']
    quiet: yes
- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- name: Include tls
  include_tasks: tls.yml
  when: virtproxyd_cfg.x509 is defined

- name: Include config
  include_tasks: config.yml
  when: ansible_distribution != "Ubuntu"

- name: add users to group
  user:
    name: "{{ item }}"
    state: present
    groups: "{{ _libvirt_group }}"
    append: yes
  loop: "{{ libvirt_group_members }}"

- include_tasks: dir_pool.yml
  loop: "{{ libvirt_storage_pools }}"
  loop_control:
    loop_var: pool

#- include_tasks: network.yml
#  loop: "{{ libvirt_networks }}"
#  loop_control:
#    loop_var: network
