- name: Refresh
  ansible.windows.win_command: gpupdate /force

- name: Install windows features - RSAT-ADDS
  win_feature:
    name: RSAT-ADDS
    state: present
    include_management_tools: yes
    include_sub_features: yes
  register: features_rsat

- name: Install ADCSTemplate module
  win_psmodule:
    name: ADCSTemplate
    skip_publisher_check: yes
    state: present

- name: create a directory for templates
  win_file: 
    path: c:\setup
    state: directory

- name: Copy templates json
  win_copy:
    src: "files/{{item}}.json"
    dest: "C:\\setup\\{{item}}.json"
  with_items: "{{cert_templates}}"

- name: Install templates
  win_shell: |
    if (-not(Get-ADCSTemplate -DisplayName "{{item}}")) { New-ADCSTemplate -DisplayName "{{item}}" -JSON (Get-Content c:\setup\{{item}}.json -Raw) -Identity "{{domain_name}}\Domain Users" -Publish }
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{domain_name}}\\Administrator"
    ansible_become_password: "{{domain_password}}"
  with_items: "{{cert_templates}}"

- name: "Configure ATTRIBUTESUBJECTALTNAME2 on CA - ESC6"
  win_shell: |
    certutil -config "{{cauthority_server}}\{{cauthority_common_name}}" -setreg policy\Editflags +EDITF_ATTRIBUTESUBJECTALTNAME2
  when: ca_vulns is defined and "'ESC6' in ca_vulns"
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{domain_name}}\\Administrator"
    ansible_become_password: "{{domain_password}}"
    cauthority_server: "{{hostname}}"
    cauthority_common_name: "{{ca_common_name}}"

- name: Refresh
  ansible.windows.win_command: gpupdate /force