---
# Load datas

# set AD datas ==================================================================================================

- name: ADCS
  hosts: adcs
  roles:
  - { role: 'windows_domain/adcs/adcs', tags: 'adcs'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.domains[domain].domain_password}}"
    ca_common_name: "{{lab.domains[domain].ca_name}}"

- name: ADCS
  hosts: adcs
  roles:
  - { role: 'windows_domain/adcs/templates', tags: 'adcs_templates', when: cert_templates is defined and cert_templates|length > 0}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.domains[domain].domain_password}}"
    ca_common_name: "{{lab.domains[domain].ca_name}}"
    ca_host: "{{lab.domains[domain].ca_server}}"
