#- name: Root DC AD configuration
#  hosts: dc
#  tags: 'build_domains_parents_domains'
#  roles:
#    - { role: 'windows_domain/domain_root', tags: 'dc_main_domains'}
#  vars:
#    domain: "{{lab.hosts[dict_key].domain}}"
#    domain_password: "{{lab.domains[domain].domain_password}}"
#    netbios_name: "{{lab.domains[domain].netbios_name}}"

- name: Child DC AD configuration
  hosts: dc
  tags: 'build_domains_child_domains'
  roles:
    - { role: 'windows_domain/domain_child', tags: 'child_domain'}
    - { role: 'windows_domain/dns_conditional_forwarder', tags: 'dns_conditional_forwarder' }
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_password: "{{lab.domains[domain].domain_password}}"
    netbios_name: "{{lab.domains[domain].netbios_name}}"
    parent_domain: "{{'.'.join(domain.split('.')[1:])}}"
    parent_domain_password: "{{lab.domains[parent_domain].domain_password}}"
    source_dc: "{{lab.hosts[lab.domains[parent_domain].dc].hostname}}.{{parent_domain}}"
    zone_name: "{{parent_domain}}"
    remote_dc: "{{lab.domains[parent_domain].dc}}"
    master_server: "{{hostvars[remote_dc].ansible_host}}"
    replication: "none"
