---
- name: "Read data files {{data_path}}/netrunner.json"
  hosts: all
  connection: local
  vars_files:
    - "{{data_path}}/netrunner.json"
  tasks:
    - name: save the Json data to a Variable as a Fact
      set_fact:
        lab: "{{lab}}"
        cacheable: yes
