---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "/etc/ansible/inventory_labs"
  tags: 'data'
  
- name: GMSA inside AD
  hosts: dc
  roles:
  - { role: 'windows_domain/gmsa', tags: 'gmsa'}
  vars:
    ad_gmsa: "{{lab.domains[lab.hosts[dict_key].domain].gmsa | default({})}}"
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.domains[domain].domain_password}}"

- name: GMSA hosts
  hosts: domain_server, domain_workstation
  roles:
  - { role: 'windows_domain/gmsa_hosts', tags: 'gmsa'}
  vars:
    ad_gmsa: "{{lab.domains[lab.hosts[dict_key].domain].gmsa | default({})}}"
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.domains[domain].domain_password}}"
    hostname: "{{lab.hosts[dict_key].hostname}}"
