---
- include_tasks: fw_rules.yml
- include_tasks: fw_profiles.yml
# Change network profile of domainAuthenticated interface 
# https://woshub.com/how-to-change-a-network-type-from-public-to-private-in-windows/
- include_tasks: net_profiles.yml
