---
- include_tasks: variables.yml
- include_tasks: asserts.yml

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- name: Generate ssh key for rclone keepass
  openssh_keypair:
    path: "{{ item.key_path }}"
    owner: "{{ item.login }}"
    group: "{{ item.group }}"
    mode: 0600
  loop: "{{ rclone_backups }}"

- name: Create local_dirs
  file:
    state: directory
    path: "{{ item.local_dir }}"
    owner: "{{ item.login }}"
    group: "{{ item.group }}"
    mode: 0700
  loop: "{{ rclone_backups }}"

- name: Install backup script
  copy:
    src: rclone-backup.sh
    dest: /usr/bin/rclone-backup.sh
    owner: root
    group: root
    mode: 0740

- name: Install retore script
  copy:
    src: rclone-restore.sh
    dest: /usr/bin/rclone-restore.sh
    owner: root
    group: root
    mode: 0740

- name: Create timer
  template:
    src: templates/rclone-backup.timer.j2
    dest: /etc/systemd/system/rclone-backup.timer
    owner: root
    group: root
    mode: 0640
  notify: restart timer
- name: Create service
  template:
    src: templates/rclone-backup.service.j2
    dest: /etc/systemd/system/rclone-backup.service
    owner: root
    group: root
    mode: 0640
  notify: restart timer



- name: Install cron
  template:
    src: rclone-backup.cron.j2
    dest: "/etc/cron.d/rclone-backup.{{ item.login }}.cron"
    owner: root
    group: root
    mode: 0644
  loop: "{{ rclone_backups }}"

