- name: Create SQL Linked server and enable RPC
  win_shell: |
    SqlCmd -E -Q "EXEC master.dbo.sp_addlinkedserver @server = N'{{item.key}}', @srvproduct=N'', @provider=N'SQLOLEDB', @datasrc=N'{{item.value.data_src}}'"
    SqlCmd -E -Q "EXEC master.dbo.sp_serveroption @server=N'{{item.key}}', @optname=N'rpc', @optvalue=N'true'"
    SqlCmd -E -Q "EXEC master.dbo.sp_serveroption @server=N'{{item.key}}', @optname=N'rpc out', @optvalue=N'true'"
  become: yes
  become_method: runas
  become_user: "{{SQLSVCACCOUNT}}"
  vars:
    ansible_become_pass: "{{SQLSVCPASSWORD}}"
  with_dict: "{{linked_servers}}"
  when: ISGMSA == false 

- name: Create SQL Linked server and enable RPC
  win_shell: |
    c:\setup\PSExec64.exe -accepteula -i -u {{SQLSVCACCOUNT}} -p ~ SqlCmd -E -Q "EXEC master.dbo.sp_addlinkedserver @server = N'{{item.key}}', @srvproduct=N'', @provider=N'SQLOLEDB', @datasrc=N'{{item.value.data_src}}'"
    c:\setup\PSExec64.exe -accepteula -i -u {{SQLSVCACCOUNT}} -p ~ SqlCmd -E -Q "EXEC master.dbo.sp_serveroption @server=N'{{item.key}}', @optname=N'rpc', @optvalue=N'true'"
    c:\setup\PSExec64.exe -accepteula -i -u {{SQLSVCACCOUNT}} -p ~ SqlCmd -E -Q "EXEC master.dbo.sp_serveroption @server=N'{{item.key}}', @optname=N'rpc out', @optvalue=N'true'"
  with_dict: "{{linked_servers}}"
  when: ISGMSA 

- name: "create logins"
  include_tasks: logins.yml  
  vars:
    linked_server: "{{item.key}}"
    users_mapping: "{{item.value.users_mapping}}"
  with_dict: "{{linked_servers}}"

- name: default login impersonation
  win_shell: |
    SqlCmd -E -Q "EXEC master.dbo.sp_addlinkedsrvlogin @rmtsrvname = N'{{item.key}}', @locallogin = NULL , @useself = N'True'"
  become: yes
  become_method: runas
  become_user: "{{SQLSVCACCOUNT}}"
  vars:
    ansible_become_pass: "{{SQLSVCPASSWORD}}"
  with_dict: "{{linked_servers}}"
  when: ISGMSA == false 

- name: default login impersonation
  win_shell: |
    c:\setup\PSExec64.exe -accepteula -i -u {{SQLSVCACCOUNT}} -p ~ SqlCmd -E -Q "EXEC master.dbo.sp_addlinkedsrvlogin @rmtsrvname = N'{{item.key}}', @locallogin = NULL , @useself = N'True'"
  with_dict: "{{linked_servers}}"
  when: ISGMSA 
