---
- name: Update repo and cache
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600

- name: Upgrade all packages on servers
  apt:
    upgrade: dist
    force_apt_get: true
- name: Check if a reboot is needed on all servers
  register: __reboot_required_file
  stat:
    path: /var/run/reboot-required
  changed_when: __reboot_required_file.stat.exists == true
