---
- include_tasks: variables.yml
- include_tasks: asserts.yml

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- include_tasks: init.yml
- include_tasks: config.yml


- name: Create pgsql users
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(_pgsql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(_pgsql_unix_socket_directories[0]) }}"
    port: "{{ item.port | default(omit) }}"
  with_items: "{{ pgsql_users }}"
  no_log: "{{ pg_users_no_log }}"
  become: true
  become_user: "{{ _pgsql_user }}"
  vars:
    ansible_ssh_pipelining: true
  environment:
    PGOPTIONS: "{{ (_pgsql_auth_method == 'scram-sha-256') | ternary('-c password_encryption=scram-sha-256', '') }}"

- name: Create databases
  postgresql_db:
    name: "{{ item.name }}"
    lc_collate: "{{ item.lc_collate | default('en_US.UTF-8') }}"
    lc_ctype: "{{ item.lc_ctype | default('en_US.UTF-8') }}"
    encoding: "{{ item.encoding | default('UTF-8') }}"
    template: "{{ item.template | default('template0') }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(_pgsql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(_pgsql_unix_socket_directories[0]) }}"
    port: "{{ item.port | default(omit) }}"
    owner: "{{ item.owner | default(_pgsql_user) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ pgsql_databases }}"
  become: true
  become_user: "{{ _pgsql_user }}"
  vars:
    ansible_ssh_pipelining: true

- name: Finish users config 
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    db: "{{ item.db | default(omit) }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(_pgsql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(_pgsql_unix_socket_directories[0]) }}"
    port: "{{ item.port | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ pgsql_users }}"
  no_log: "{{ pg_users_no_log }}"
  become: true
  become_user: "{{ _pgsql_user }}"
  vars:
    ansible_ssh_pipelining: true
  environment:
    PGOPTIONS: "{{ (_pgsql_auth_method == 'scram-sha-256') | ternary('-c password_encryption=scram-sha-256', '') }}"
