---
#- debug:
#    var: firewall_rules

#https://github.com/dsccommunity/NetworkingDsc/wiki/Firewall
- name: Create firewall rules
  win_dsc:
    resource_name:  xFirewall
    Name:           "{{ item.value.name}}"
    Ensure:         present
    Enabled:        "{{item.value.enabled | default(true)}}"
    Action:         "{{item.value.action | default('Allow')}}"
    Profile:        "{{item.value.profiles | default([])}}"
    Direction:      "{{item.value.direction | default('Inbound')}}"
    LocalAddress:   "{{item.value.localip | default('Any')}}"
    Localport:      "{{item.value.localport | default('Any')}}"
    Protocol:       "{{item.value.protocol | default('TCP')}}"
    RemoteAddress:  "{{item.value.remoteip | default('Any')}}"
    RemotePort:     "{{item.value.remoteport | default('Any')}}"
    Group:          "{{item.value.group | default('ansible')}}"
  with_dict: "{{firewall_rules}}"

