- name: Install AUR packages
  include_role:
    name: aur-install
  vars:
    aur_pkg_name: "{{ item }}"
  loop:
    - xpub
    - batify
- name: Install pacman packages
  pacman:
    name: "{{ item }}"
    update_cache: true
  register: __pacman
  changed_when: (__pacman.packages | default([]))| length >0 
  loop:
    - dunst
