---
- name: assert proper distribution
  assert:
    that:
      - ansible_distribution in ['Archlinux']
    quiet: true
- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Include common variables
  include_vars: "common.yml"

- include_tasks: asserts.yml

- include_tasks: "{{ ansible_distribution }}.yml" 
- name: Get installed packages
  ansible.builtin.package_facts:
    manager: "auto"

- name: Install batify rule 
  template:
    src: templates/99-batify.rules.j2
    dest: /etc/udev/rules.d/99-batify.rules
    owner: root
    group: root
    mode: 0644