---
- name: assert proper distribution
  assert:
    that:
      - ansible_distribution in ['Archlinux']
    quiet: true

- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Include common variables
  include_vars: "common.yml"

- include_tasks: asserts.yml

- include_tasks: "{{ ansible_distribution }}.yml"
