---
- import_playbook: books/test2.yml
#- import_playbook: books/test.yml
#  vars:
#    data_path: "/etc/ansible/lab_inventories/netrunner"
#  tags: 'data'
#- import_playbook: books/lab_data.yml

#- import_playbook: books/debug.yml

#- import_playbook: books/computers-build.yml
#- import_playbook: books/domains-build.yml
#- import_playbook: books/domains-add-members.yml
##### IL Y A ENCORE DES TRUCS A FAIRE SUR LE BIDIRECTIONNEL VS INBOUND
#- import_playbook: books/build-trusts.yml


#- import_playbook: books/ad-data.yml
#- import_playbook: books/gmsa.yml
#- import_playbook: books/laps.yml
#- import_playbook: books/adcs.yml
#- import_playbook: books/local-groups-users-rights.yml
#- import_playbook: books/ad-groups-foreign-members.yml
#- import_playbook: books/ad-acl.yml
#- import_playbook: books/iis.yml
#- import_playbook: books/mssql.yml
#- import_playbook: books/webdav.yml

## TO DO DEFENDER + APPOCKER
#- import_playbook: books/security.yml


# TO DO
#- import_playbook: books/vulnerabilities.yml

#- import_playbook: books/reboot.yml
# ##################
#  TO CONTINUE
# ##################

#- name: finish servers
#  hosts: domain_server
#  roles:
#    - { role: 'windows_domain/install_features', tags: 'install_features'}
#    - { role: 'windows_domain/install_softwares', tags: 'install_softwares' }
#    #- { role: 'windows_domain/clone_repos', tags: 'repos'}
#    - { role: 'windows_domain/download_files', tags: 'download_files' }
#  vars:
#    hostname: "{{lab.hosts[dict_key].hostname}}"
#    domain: "{{lab.hosts[dict_key].domain}}"
#    features: "{{lab.hosts[dict_key].features}}"
#    softwares: "{{lab.hosts[dict_key].softwares}}"
#    repos: "{{lab.hosts[dict_key].repos}}"
#    download_files: "{{lab.hosts[dict_key].download_files}}"
#    domain_username: "{{domain}}\\Administrator"
#    domain_password: "{{lab.domains[domain].domain_password}}"
#    domain_server: "{{lab.hosts[dict_key].hostname}}.{{domain}}"