---
- import_playbook: books/lab_data.yml
  vars:
    data_path: "/etc/ansible/lab_inventories/{{domain_name}}"
  tags: 'data'

#- import_playbook: books/debug.yml

#- import_playbook: books/build-computers.yml
#- import_playbook: books/build-domains.yml
#- import_playbook: books/domain-members.yml
#- import_playbook: books/build-trusts.yml
- import_playbook: books/ad-data.yml
- import_playbook: books/gmsa.yml
- import_playbook: books/laps.yml
- import_playbook: books/adcs.yml
- import_playbook: books/ad-relations.yml
- import_playbook: books/ad-acl.yml
#- import_playbook: books/iis.yml
#- import_playbook: books/webdav.yml


#- import_playbook: books/mssql.yml
## SECURITY -----
# --------------------------------------------------------------------
# specifics security linked to the scenario are here
#- import_playbook: books/security.yml
# --------------------------------------------------------------------
# specifics vulns linked to the scenario are here
#- import_playbook: books/vulnerabilities.yml

#- import_playbook: books/reboot.yml
# ##################
#  TO CONTINUE
# ##################

#- name: finish servers
#  hosts: domain_server
#  roles:
#    - { role: 'windows_domain/install_features', tags: 'install_features'}
#    - { role: 'windows_domain/install_softwares', tags: 'install_softwares' }
#    #- { role: 'windows_domain/clone_repos', tags: 'repos'}
#    - { role: 'windows_domain/download_files', tags: 'download_files' }
#  vars:
#    hostname: "{{lab.hosts[dict_key].hostname}}"
#    domain: "{{lab.hosts[dict_key].domain}}"
#    features: "{{lab.hosts[dict_key].features}}"
#    softwares: "{{lab.hosts[dict_key].softwares}}"
#    repos: "{{lab.hosts[dict_key].repos}}"
#    download_files: "{{lab.hosts[dict_key].download_files}}"
#    domain_username: "{{domain}}\\Administrator"
#    domain_password: "{{lab.domains[domain].domain_password}}"
#    domain_server: "{{lab.hosts[dict_key].hostname}}.{{domain}}"