---
- import_playbook: netrunner/data.yml
  vars:
    data_path: "/etc/ansible/inventory_labs"
  tags: 'data'
#- import_playbook: netrunner/debug.yml

#- import_playbook: netrunner/build-computers.yml
#- import_playbook: netrunner/build-domains.yml
#- import_playbook: netrunner/domain-members.yml
#- import_playbook: netrunner/build-trusts.yml
- import_playbook: netrunner/ad-data.yml
#- import_playbook: netrunner/gmsa.yml
#- import_playbook: netrunner/laps.yml
#- import_playbook: netrunner/adcs.yml

# ##################
#  TO CONTINUE
# ##################

#- name: finish servers
#  hosts: domain_server
#  roles:
#    - { role: 'windows_domain/install_features', tags: 'install_features'}
#    - { role: 'windows_domain/install_softwares', tags: 'install_softwares' }
#    #- { role: 'windows_domain/clone_repos', tags: 'repos'}
#    - { role: 'windows_domain/download_files', tags: 'download_files' }
#  vars:
#    hostname: "{{lab.hosts[dict_key].hostname}}"
#    domain: "{{lab.hosts[dict_key].domain}}"
#    features: "{{lab.hosts[dict_key].features}}"
#    softwares: "{{lab.hosts[dict_key].softwares}}"
#    repos: "{{lab.hosts[dict_key].repos}}"
#    download_files: "{{lab.hosts[dict_key].download_files}}"
#    domain_username: "{{domain}}\\Administrator"
#    domain_password: "{{lab.domains[domain].domain_password}}"
#    domain_server: "{{lab.hosts[dict_key].hostname}}.{{domain}}"