- name: process permssion
  include_tasks: permission.yml
  with_items: "{{laps_readers}}"
  loop_control:
     loop_var: principal
  when: laps_readers is defined and laps_path != false and laps_path | length > 0