# https://clintboessen.blogspot.com/2010/04/group-scopes.html
# https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc755692(v=ws.10)



- name: Create domain groups
  microsoft.ad.group:
    name: "{{ item.key }}"
    scope: "{{item.value.scope | default('domainlocal')}}"
    path: "{{item.value.path}}"
    managed_by: "{{item.value.managed_by | default('')}}"
    state: present
    domain_username: "{{domain_name}}\\Administrator"
    domain_password: "{{domain_password}}"
  with_dict: "{{ad_groups}}"
  when: action == "create"

- name: "synchronizes all domains before adding members to groups"
  win_shell: repadmin /syncall /Ade
  become: yes
  become_method: runas
  become_user: "{{domain_name}}\\Administrator"
  vars:
    ansible_become_pass: "{{domain_password}}"
  when: action == "add_members"

- name: "Create members to domain groups"
  community.windows.win_domain_group_membership:
    domain_username: "{{domain_name}}\\Administrator"
    domain_password: "{{domain_password}}"
    name: "{{item.key}}"
    members: "{{item.value.members}}"
    state: Present
  with_dict: "{{ ad_groups }}"
  when: action == "add_members"
  register: group_membership
  until: "group_membership is not failed"
  retries: 3
  delay: 60


#- name: Create members to domain groups 
#  microsoft.ad.group:
#    name: "{{ item.key }}"
#    path: "{{item.value.path}}"
#    members: 
#      set: "{{item.value.members}}"
#    state: present
#    domain_username: "{{domain_name}}\\Administrator"
#    domain_password: "{{domain_password}}"
#  with_dict: "{{ad_groups}}"

