---
_conf_list: []
_libvirt_group: libvirt
_libvirt_socket_dir: /run/libvirt

_libvirt_systemd_files:
  libvirtd:
    - libvirtd.service
    - libvirtd-admin.socket
    - libvirtd.socket
    - libvirtd-ro.socket
    - libvirtd-tls.socket
    - libvirtd-tcp.socket
  virtproxyd:
    - virtproxyd.service
    - virtproxyd-admin.socket
    - virtproxyd.socket
    - virtproxyd-ro.socket
    - virtproxyd-tls.socket
    - virtproxyd-tcp.socket
  virtlogd:
    - virtlogd.service
    - virtlogd-admin.socket
    - virtlogd.socket
  virtlockd:
    - virtlockd.service
    - virtlockd-admin.socket
    - virtlockd.socket
  drivers:
    virtqemud:
      - .service
      - -admin.socket
      - -ro.socket
      - .socket
    virtinterfaced:
      - .service
      - -admin.socket
      - -ro.socket
      - .socket
    virtnodedevd:
      - .service
      - -admin.socket
      - -ro.socket
      - .socket
    virtstoraged:
      - .service
      - -admin.socket
      - -ro.socket
      - .socket
    virtnetworkd:
      - .service
      - -admin.socket
      - -ro.socket
      - .socket
    virtnwfilterd:
      - .service
      - -admin.socket
      - -ro.socket
      - .socket
    virtsecretd:
      - .service
      - -admin.socket
      - -ro.socket
      - .socket

