---
- include_tasks: variables.yml
- include_tasks: asserts.yml

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- name: udev Template
  template:
    src: templates/49-sane-missing-scanner.rules.j2
    dest: /etc/udev/rules.d/49-sane-missing-scanner.rules
    owner: root
    group: root
    mode: 0640
