
- name: create directory for repositories
  win_file: 
    path: "c:\\users\\{{user}}\\Desktop\\repositories"
    state: directory
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{net_bios}}\\{{user}}"
    ansible_become_password: "{{ password }}"
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only

- name: Install repos
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
        [String]
        $Repo,
        [String]
        $Folder,
        [String]
        $Base
      )
      if (-Not (Test-Path -Path $Base\$Folder)) {
        git clone -q $Repo $Base\$Folder
      }
    error_action: stop
    parameters:
      Repo: "{{ item[1] }}"
      Folder: "{{ item[0] }}"
      Base: "c:\\users\\{{user}}\\Desktop\\repositories" 
  loop: "{{ repositories }}"
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{net_bios}}\\{{user}}"
    ansible_become_password: "{{ password }}"
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only