---
- name: Create data base dir
  file:
    path: "{{ hvault_data_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ _hvault_user }}"
    group: "{{ _hvault_group }}"

- name: Create data dir
  file:
    path: "{{ hvault_tls_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ _hvault_user }}"
    group: "{{ _hvault_group }}"

- name: Create config drop-in
  file:
    path: /etc/vault.d
    state: directory
    mode: "0755"
    owner: "{{ _hvault_user }}"
    group: "{{ _hvault_group }}"

- name: Install env
  file:
    path: /etc/vault.env
    owner: "{{ _hvault_user }}"
    group: "{{ _hvault_group }}"
    mode: "0644"
    state: touch

- name: Install vault.service
  template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: "0644"

- name: Stat TLS key
  stat:
    path: "{{ hvault_tls_dir }}/{{ hvault_tls_key }}"
  register: __tls_key

- name: Generate TLS
  block:
    - name: create TLS key
      openssl_privatekey:
        path: "{{ hvault_tls_dir }}/{{ hvault_tls_key }}"
        size: 4096
        state: present
        owner: "{{ _hvault_user }}"
        group: "{{ _hvault_group }}"

    - name: create CSR
      openssl_csr:
        path: "{{ hvault_tls_dir }}/{{ hvault_tls_cert }}.csr"
        privatekey_path: "{{ hvault_tls_dir }}/{{ hvault_tls_key }}"
        key_usage_critical: true
        key_usage:
          - digitalSignature
          - keyEncipherment
        basic_constraints_critical: true
        basic_constraints:
          - 'CA:TRUE'
        common_name: "Self Signed Vault"
        subject_alt_name: "IP:{{ inventory_hostname }}"
        use_common_name_for_san: false

    - name: sign CSR
      openssl_certificate:
        path: "{{ hvault_tls_dir }}/{{ hvault_tls_cert }}"
        csr_path: "{{ hvault_tls_dir }}/{{ hvault_tls_cert }}.csr"
        privatekey_path: "{{ hvault_tls_dir }}/{{ hvault_tls_key }}"
        provider: selfsigned
  when: not __tls_key.stat.exists

- name: Install config
  template:
    src: vault.hcl.j2
    dest: /etc/vault.hcl
    owner: "{{ _hvault_user }}"
    group: "{{ _hvault_group }}"
    mode: "0644"
  notify: restart vault

- name: flush_handlers
  meta: flush_handlers
