---
# defaults file for pki

# root-ca or intermediate-ca
ca_type: root-ca
# empty for root ca
ca_signing_ca:

ca_base_dir: /etc/ssl/ca
ca_certs_dir: certs
ca_cnf_dir: configs
ca_cnf_req_dir: req
ca_cnf_ca_dir: ca
ca_new_certs_dir: new-certs
ca_crl_dir: crl
ca_private_dir: private
ca_csr_dir: csr
ca_signed_csr_dir: csr-signed
ca_rejected_csr_dir: csr-rejected

ca_crlnumber: "crlnumber"
ca_serial: "serial"
ca_database: "db"
db_unique_subject: "yes"

ca_file_basename: "ca-{{ ansible_hostname }}"
ca_key_password: "test"

ca_cps: "http://my.policy.uri"
ca_cps_explicit: "some explicit test for policy"
ca_cps_organization: "my org"
ca_crldp_uri: "http://my.crl.uri"
ca_aia_uri: "http://my.cert.uri"
ca_ocsp_uri: "http://my.ocsp.uri"

ca_templates: {
  TSL-server: default,
  TLS-client: default,
  TLS-client_server: default,
  identity: default,
  encryption: default,
  intermediate-ca: default,
  root-ca: default
}
ca_templates_params: {
  default: {
    default_bits: 2048,
    default_days: 375,
    default_md: sha256,
    policy: {
      OrganizationUnitName: match
    }
  }
}

ca_self_info: {
  duration: 7300,
  default_bits: 4096,
  default_md: sha256,
  dn: {
    CN: My CA,
  }
}
