#- name: Set servers for pacman
#  lineinfile:
#    path: /etc/pacman.conf
#    state: present
#    line: "# seblu: virtualbox ext oracle"
#
#- name: Set servers for pacman
#  lineinfile:
#    path: /etc/pacman.conf
#    state: present
#    line: "[seblu]"
#    insertafter: "# seblu: virtualbox ext oracle"
#
#- name: Set servers for pacman
#  lineinfile:
#    path: /etc/pacman.conf
#    state: present
#    line: "Server={{ item }}"
#    insertafter: "[seblu]"
#  with_items: "{{ vbox_extra_repos }}"

- name: Install virtualbox
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  register: __pacman
  changed_when: (__pacman.packages | default([]))| length >0 
  loop:
    - linux-lts-headers
    - virtualbox
    - virtualbox-host-dkms

- name: Install virtualbox-ext-oracle
  include_role:
    name: aur-install
  vars:
    aur_pkg_name: virtualbox-ext-oracle
