
#"StefanScherer/windows_10"
#"StefanScherer/windows_11"
#"StefanScherer/windows_2019"
#"gusztavvargadr/windows-10"
#"gusztavvargadr/windows-11"
#"gusztavvargadr/windows-server-core"
#"gusztavvargadr/windows-server"
#"archlinux/archlinux"


Vagrant.configure("2") do |config|
  # Uncomment this depending on the provider you want to use
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
  #ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_desktop'
  net_defs = { 
  	haas:     {name: "haas",     mask: "255.255.255.0", network: "172.16.0.0", gw: "172.16.0.254"},
  	weyland:  {name: "weyland",  mask: "255.255.255.0", network: "172.16.1.0", gw: "172.16.1.254"},
  	research: {name: "research", mask: "255.255.255.0", network: "172.16.2.0", gw: "172.16.2.254"},
#    bridge: {name: "br0", mask: "255.255.255.0", network: "192.168.2.0", gw: "192.168.2.1"}
    bridge: {name: "br1", mask: "255.255.255.0", network: "192.168.58.0", gw: "192.168.2.1"}
  }
  boxes = [
    { 
      # only internal
      bname: "win_dev", 
      ip: "192.168.56.10", 
  	  net: net_defs[:haas], 
      box: "gusztavvargadr/windows-11", 
      box_version: "2302.0.2409", 
      os: "windows", 
      ram: 4096, 
      cpu: 2
    }
  ]

  # disable rdp forwarded port inherited from StefanScherer box
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true, disabled: true
  # no autoupdate if vagrant-vbguest is installed
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 10
  config.winrm.transport = "plaintext"
  config.winrm.basic_auth_only = true

  boxes.each do |box|
    config.vm.define box[:bname] do |target|
      # BOX
      target.vm.provider "virtualbox" do |v|
        v.memory = box[:ram]
        v.name = box[:bname]
        v.cpus = 2
      end
      # Download image
      target.vm.box_download_insecure = box[:box]
      target.vm.box = box[:box]
      if box.has_key?(:box_version)
        target.vm.box_version = box[:box_version]
      end

      # issues/49
      target.vm.synced_folder '.', '/vagrant', disabled: true
      target.vm.synced_folder 'shared/', '/shared', disabled: true

      # Windows specific
      target.vm.guest = :windows
      target.vm.communicator = "winrm"
      #  alway provision an internal network on Ethernet 2
      n_info = box[:net]
      # target.vm.network :private_network, ip: box[:ip], virtualbox__intnet: n_info[:name]
      target.vm.network :private_network, ip: box[:ip]
      #target.vm.provision :shell, :path => "../scripts/fix_ip.ps1", privileged: false, args: ["Ethernet 2", box[:ip], n_info[:mask], n_info[:gw]]
      #if box.has_key?(:ip_p)
      #  n_info_p = net_defs[:bridge]
      #  #  Provision a public interface if needed on Ethernet 3 
      #  target.vm.network :public_network, bridge: n_info_p[:name], ip: box[:ip_p]
      #  target.vm.provision :shell, :path => "./scripts/all_in_one.ps1", privileged: false, args: ["-IFName", "Ethernet 3", "-IP", box[:ip_p], "-Mask", n_info_p[:mask]]
      #end
      target.vm.provision :shell, :path => "../../scripts/all_in_one.ps1", privileged: false

      if box.has_key?(:forwarded_port)
        # forwarded port explicit
        box[:forwarded_port] do |forwarded_port|
          target.vm.network :forwarded_port, guest: forwarded_port[:guest], host: forwarded_port[:host], host_ip: "127.0.0.1", id: forwarded_port[:id]
        end
      end
    end
  end
end