- name: Install-WindowsFeature RSAT-AD-PowerShell
  ansible.windows.win_feature:
    name: RSAT-AD-PowerShell 
    state: present
  when: installed_gmsa | default([]) | length > 0

- name: refresh krb token
  win_shell:  klist -li 0x3e7 purge

- name: Install ADServiceAccount
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
        param (
          [String]
          $gMSA_Name
      )
      Install-ADServiceAccount -Identity $gMSA_Name
    error_action: stop
    parameters:
        gMSA_Name: "{{item}}"
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{domain_name}}\\Administrator"
    ansible_become_password: "{{domain_password}}"
  with_items: "{{ installed_gmsa }}"