galaxy_info:
  role_name: blackarch
  author: jubeaz
  description: install BlackArch Linux over Archlinux
  license: GPL-2.0-or-later
  min_ansible_version: 2.1
  platforms:
    - name: Archlinux
      versions:
        - all
  galaxy_tags: []
dependencies: []
