domain_users: {
    "emoon" : {
        "firstname"       : "Estelle",
        "surname"         : "Moon",
        "password"        : "Nps4ffWx7omDc5_h", 
        "city"            : "-",
        "description"     : "",
        "groups"          : ["L_LAPS_READER"],
        "path"            : "CN=Users,DC=haas,DC=local"
        },
    "imcguire" : {
        "firstname"       : "Isabel",
        "surname"         : "McGuire",
        "password"        : "zazc9DN_KpftZAvn", 
        "city"            : "-",
        "description"     : "",
        "groups"          : [],
        "path"            : "CN=Users,DC=haas,DC=local"
        },
    "mbellamy" : {
        "firstname"       : "Mason",
        "surname"         : "Bellamy",
        "password"        : "b_QNoDKoVJTjU3gq", 
        "city"            : "-",
        "description"     : "",
        "groups"          : ["Domain Admins"],
        "path"            : "CN=Users,DC=haas,DC=local"
        },
    "mhendrik" : {
        "firstname"       : "Mr.",
        "surname"         : "Hendrik",
        "password"        : "b_QNoDKoVJTjU3gq", 
        "city"            : "-",
        "description"     : "DB link user",
        "groups"          : [],
        "path"            : "CN=Users,DC=haas,DC=local"
        },
    "rknight" : {
        "firstname"       : "Ryon",
        "surname"         : "Knight",
        "password"        : "5jqkKJJjmqup_o_E", 
        "city"            : "-",
        "description"     : "DB admin",
        "groups"          : [],
        "path"            : "CN=Users,DC=haas,DC=local"
        },
    "thaas" : {
        "firstname"       : "Thomas",
        "surname"         : "Haas",
        "password"        : "s_yrPbrqtHbc3n7a", 
        "city"            : "-",
        "description"     : "",
        "groups"          : [],
        "path"            : "CN=Users,DC=haas,DC=local"
        },
    "bran" : {
        "firstname"   : "bran",
        "surname"     : "v1.0",
        "password"    : "bFgJMREVx_n5mns4",
        "city"        : "-",
        "description" : "",
        "groups"      : [],
        "path"        : "CN=Users,DC=haas,DC=local",
        "spns"        : ["MSSQLSvc/fenris.haas.local:1433","MSSQLSvc/fenris.haas.local"]
        }
    }