galaxy_info:
  role_name: pki
  author: jubeaz
  description: install pki infra
  license: GPL-2.0-or-later
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
        - focal
    - name: Archlinux
      versions:
        - all
  galaxy_tags: [pki, openssl, certificate]
dependencies: []
