hostname: "archer"
type: "server" 

local_admin_password: "Jubeaz12345+-"

local_users: {
}

local_groups: {
    "Administrators" : [],
    "Remote Management Users": [],
    "Remote Desktop Users" : [],
}

local_security: {
#    "uac": { "status": "on", "level": "5" },
## 0: UAC won't prompt (like disabled)                                                                                                                                                                  │
## 1: ask for username and password to execute the binary with high rights (on Secure Desktop)                                                                                                          │
## 2: Always notify me ask for confirmation to the administrator when he tries to execute something with high privileges (on Secure Desktop)                                                            │
## 3: like 1 but not necessary on Secure Desktop                                                                                                                                                        │
## 4: like 2 but not necessary on Secure Desktop                                                                                                                                                        │
## 5: ask the administrator to confirm to run non Windows binaries with high privileges     
#    "enable_run_as_ppl" : false,
#    "windows_defender": true,
    "firewall": {
        "profiles": {
            "Domain": {"status": "enabled", "inbound": "block", "outbound": "allow"},
            "Public": {"status": "enabled", "inbound": "block", "outbound": "allow"},
            "Private": {"status": "enabled", "inbound": "allow", "outbound": "allow"},
            # enabled, disabled, # ["Domain", "Private", "Public"], # "allow", "block", "not_configured",  # "allow", "block", "not_configured"
        },
        "interface": {
            "Ethernet": "Private",
            "Ethernet 2": "Domain"
        },
        "rules": {
            "FTP_IN_1": {"enabled": true, "profiles": ["Domain"], "action": "allow", "direction": "in", "lip": "any", "lport": "21", "protocol": "tcp", "rip": "any", "rport": "any"},
            "FTP_IN_2": {"enabled": true, "profiles": ["Domain"], "action": "allow", "direction": "in", "lip": "any", "lport": "20", "protocol": "tcp", "rip": "any", "rport": "any"}
            # ["Domain", "Private", "Public"], # allow, block, # in, out # ip or any # port or any, 
        }
    }
}

scripts : ["sidhistory.ps1"]
vulns: ["disable_firewall"]


features: ["NET-Framework-Core"]
softwares: [  "git", "visualstudio2022community", "notepadplusplus"]
repos: [
    ["Mimikatz", "https://github.com/gentilkiwi/mimikatz.git"],
    ["Rubeus", "https://github.com/GhostPack/Rubeus"]
]
repos_user: ""
repos_password: ""
download_files: [
    ["GRMWDK_EN_7600_1.ISO", "https://download.microsoft.com/download/4/A/2/4A25C7D5-EFBE-4182-B6A9-AE6850409A78/GRMWDK_EN_7600_1.ISO"]
]

