---
- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  register: __pacman
  changed_when: (__pacman.packages | default([]))| length >0 
  loop: "{{ sane_pkgs }}"
  notify: restart ipp-usb
