# https://clintboessen.blogspot.com/2010/04/group-scopes.html
# https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc755692(v=ws.10)


- name: Create Groups Universal
  microsoft.ad.group:
    name: "{{ item.key }}"
    scope: universal
    path: "{{item.value.path}}"
    members: 
      add: "{{item.value.members}}"
    managed_by: "{{item.value.managed_by}}"
    state: present
    domain_username: "{{domain_name}}\\Administrator"
    domain_password: "{{domain_password}}"
  with_dict: "{{ ad_groups['universal'] }}"
  when: ad_groups['universal'] is defined

- name: Create Groups Global
  microsoft.ad.group:
    name: "{{ item.key }}"
    scope: global
    path: "{{item.value.path}}"
    members: 
      add: "{{item.value.members}}"
    managed_by: "{{item.value.managed_by}}"
    state: present
    domain_username: "{{domain_name}}\\Administrator"
    domain_password: "{{domain_password}}"
  with_dict: "{{ ad_groups['global'] }}"
  when: ad_groups['global'] is defined

- name: Create Groups domainlocal
  microsoft.ad.group:
    name: "{{ item.key }}"
    scope: domainlocal
    path: "{{item.value.path}}"
    members: 
      add: "{{item.value.members}}"
    managed_by: "{{item.value.managed_by}}"
    state: present
    domain_username: "{{domain_name}}\\Administrator"
    domain_password: "{{domain_password}}"
  with_dict: "{{ ad_groups['domainlocal'] }}"
  when: ad_groups['domainlocal'] is defined