- name: Ensure Administrator is part of Domain Admins
  win_domain_group_membership:
    name: "Domain Admins"
    members:
      - Administrator
    state: present

- name: organisation units
  import_tasks: ou.yml

- name: groups
  import_tasks: groups.yml

- name: users
  import_tasks: users.yml
