# DNSCHANGE
# New-NetRoute -DestinationPrefix 10.51.0.0/16 -InterfaceIndex 12 -NextHop 10.23.0.1 -RouteMetric 10
# New-NetRoute -InterfaceAlias 'Ethernet 3' -DestinationPrefix "10.0.0.0/24" -NextHop 0.0.0.0 -RouteMetric 10
# {{domain_ip}}/{{domain_prefix}}

- name: "prioritize the {{domain_adapter}} interface (local) as the default for routing"
  ansible.windows.win_shell:
    Set-NetIPInterface -InterfaceAlias "{{domain_adapter}}" -InterfaceMetric 10
  when: two_adapters == true

- name: "Set configure dns to {{domain_dc_ip}}"
  win_dns_client:
    adapter_names: "{{domain_adapter}}"
    ipv4_addresses:
    - "{{domain_dc_ip}}"
    log_path: C:\dns_log.txt

- name: Verify File Server Role is installed.
  win_feature:
    name: File-Services, FS-FileServer
    state: present
    include_management_tools: True

- name: "Add server to {{domain_name}}"
  microsoft.ad.membership:
    hostname: "{{hostname}}"
    dns_domain_name: "{{domain_name}}"
    domain_admin_user: "Administrator@{{domain_name}}"
    domain_admin_password: "{{domain_password}}"
    domain_ou_path: "{{path}}"
    state: domain
    reboot: true
  register: domain_state

