# DNSCHANGE
- name: "prioritize the {{domain_adapter}} interface (local) as the default for routing"
  ansible.windows.win_shell:
    Set-NetIPInterface -InterfaceAlias "{{domain_adapter}}" -InterfaceMetric 10
  when: two_adapters == true

- name: "Set configure dns to {{domain_dc_ip}}"
  win_dns_client:
    adapter_names: "{{domain_adapter}}"
    ipv4_addresses:
    - "{{domain_dc_ip}}"
    log_path: C:\dns_log.txt

- name: Verify File Server Role is installed.
  win_feature:
    name: File-Services, FS-FileServer
    state: present
    include_management_tools: True

- name: "Add server to {{domain_name}}"
  win_domain_membership:
    dns_domain_name: "{{domain_name}}"
    domain_admin_user: "Administrator@{{domain_name}}"
    domain_admin_password: "{{domain_password}}"
#    domain_ou_path: "{{member_domain_ou_path}}"
    state: domain
  register: domain_state

- name: Reboot if needed
  win_reboot:
    reboot_timeout: 1500
    post_reboot_delay: 100
  when: domain_state.reboot_required

