cert_templates: ["ESC1", "ESC2"]
ca_vulns: ["ESC6"]
web_enrollment: true # ESC8
ca_common_name: "internal-ca"

acls_adcs_templates: {
  # 'FullControl', 'Read', 'Write', 'Enroll', 'Autoenroll'.
  "fullcontrol_arose_esc1" : {"for": "arose", "to": "ESC1", "right": "FullControl", "inheritance": "None"}
}
