mssql: {
    "sa_password": "_r3QFLi5EnkfQU_4",
    "svcaccount" : "eli",
    "sysadmins" : ["WEYLAND\\acorrea"],
    "executeaslogin" : {
        "WEYLAND\\anson" :  "WEYLAND\\acorrea"
      },
    "executeasuser" : {
        "master_dbo": {
            "user": "WEYLAND\\acorrea",
            "db"  : "master",
            "impersonate" : "dbo"
          },
        "dbms_dbo": {
            "user": "WEYLAND\\acorrea",
            "db"  : "msdb",
            "impersonate" : "dbo"
          }
      },
    "linked_servers": {
        "fenris" : {
            "data_src": "fenris.haas.local",
            "users_mapping": [
                {"local_login": "WEYLAND\\acorrea","remote_login": "sa", "remote_password": "ftrum_Ya5d7DCQQN"}
              ]
            }
        }
    }