
- name: debug
  debug:
    var: outer_item.key

- name: debug
  debug:
    var: outer_item.value.spns

- name: "set computers SPN"
  microsoft.ad.computer:
    name: "{{ outer_item.key }}"
    path: "{{outer_item.value.path}}"
    spn: 
      add: 
        - "{{item}}"
    domain_username: "{{domain_name}}\\Administrator"
    domain_password: "{{domain_password}}"
  loop: "{{ outer_item.value.spns }}"