---
libvirt_storage_pools:
#  - name: 
#    path:
    
libvirt_networks:
#  - name:
#    mode:
#    ip:
#    netmask:
#    dhcp_start:
#    dhcp_end:


libvirt_group_members:
deployment_type: modular #modular or monolithic
libvirt_key_path: /etc/pki/libvirt/private
libvirt_key_file: key.pem
libvirt_cert_path: /etc/pki/libvirt
libvirt_cert_file: cert.pem
libvirt_ca_path: /etc/pki/CA
libvirt_ca_cert_file: cacert.pem
libvirt_ca_crl_file: crl.pem

libvirtd_cfg: {
  usocket: {
    ro_perms: "0666", # 0666,
    rw_perms: "0660", # 0666,
    admin_perms: "0600", # 0600
    group: "{{ _libvirt_group }}"
  },
  network: {
    tls_listen_stream: 16514, # 127.0.0.1:16514,
      #tcp_listen_stream: 16509 # 127.0.0.1:16514
  },
  auth: {
    auth_unix_ro: '"none"', # polkit,
    auth_unix_rw: '"none"', # polkit,
    #auth_tcp = '"sasl"',
    auth_tls: '"none"',
    # tcp_min_ssf = 112,
    access_drivers: '[ "none" ]'
  },
  x509: {
    key_file: '"{{ libvirt_key_path }}/{{ libvirt_key_file }}"',
    cert_file: '"{{ libvirt_cert_path }}/{{ libvirt_cert_file }}"',
    ca_file: '"{{ libvirt_ca_path }}/{{ libvirt_ca_cert_file }}"',
    # crl_file: '"{{ libvirt_ca_path }}/{{ libvirt_ca_crl_file }}"'
  },
  auth_controls: {
    tls_no_sanity_certificate: 0,
    tls_no_verify_certificate: 0,
    #    tls_allowed_dn_list: '["DN1", "DN2"]',
    #    tls_priority: '"NORMAL"',
    #    sasl_allowed_username_list: '["joe@EXAMPLE.COM", "fred@EXAMPLE.COM" ]'
  },
  process_controls: {
    #max_clients: 5000,
    #max_queued_clients: 1000,
    #max_anonymous_clients: 20,
    #min_workers: 5,
    #max_workers: 20,
    #prio_workers: 5,
    #max_client_requests: 5,
    #admin_min_workers: 1,
    #admin_max_workers: 5,
    #admin_max_clients: 5,
    #admin_max_queued_clients: 5,
    #admin_max_client_requests: 5
  },
  log_controls: {
    log_level: 3,
      #log_filters: '"1:qemu 1:libvirt 4:object 4:json 4:event 1:util"',
    log_outputs: '"3:journald"'
  },
  autiting: {
    #audit_level = 2,
    #audit_logging: 1
  },
  uuid: {
    #host_uuid: '"00000000-0000-0000-0000-000000000000"',
    host_uuid_source: '"smbios"'
  },
  keepalive: {
    #keepalive_interval: 5,
    #keepalive_count: 5,
    #keepalive_required: 1,
    #admin_keepalive_required: 1,
    #admin_keepalive_interval: 5,
    #admin_keepalive_count: 5
  },
  ovs: {
    #timeout: 5
  }
}

virtproxyd_cfg: {
  usocket: {
    ro_perms: "0666", # 0666,
    rw_perms: "0660", # 0666,
    admin_perms: "0600", # 0600
    group: "{{ _libvirt_group }}"
  },
  network: {
    tls_listen_stream: 16514, # 127.0.0.1:16514,
      #tcp_listen_stream: 16509 # 127.0.0.1:16514
  },
  auth: {
    auth_unix_ro: '"none"', # polkit,
    auth_unix_rw: '"none"', # polkit,
    #auth_tcp = '"sasl"',
    auth_tls: '"none"',
    # tcp_min_ssf = 112,
    access_drivers: '[ "none" ]'
  },
  x509: {
    key_file: '"{{ libvirt_key_path }}/{{ libvirt_key_file }}"',
    cert_file: '"{{ libvirt_cert_path }}/{{ libvirt_cert_file }}"',
    ca_file: '"{{ libvirt_ca_path }}/{{ libvirt_ca_cert_file }}"',
    # crl_file: '"{{ libvirt_ca_path }}/{{ libvirt_ca_crl_file }}"'
  },
  auth_controls: {
    tls_no_sanity_certificate: 0,
    tls_no_verify_certificate: 0,
    #    tls_allowed_dn_list: '["DN1", "DN2"]',
    #    tls_priority: '"NORMAL"',
    #    sasl_allowed_username_list: '["joe@EXAMPLE.COM", "fred@EXAMPLE.COM" ]'
  },
  process_controls: {
    #max_clients: 5000,
    #max_queued_clients: 1000,
    #max_anonymous_clients: 20,
    #min_workers: 5,
    #max_workers: 20,
    #prio_workers: 5,
    #max_client_requests: 5,
    #admin_min_workers: 1,
    #admin_max_workers: 5,
    #admin_max_clients: 5,
    #admin_max_queued_clients: 5,
    #admin_max_client_requests: 5
  },
  log_controls: {
    log_level: 1,
      #log_filters: '"1:qemu 1:libvirt 4:object 4:json 4:event 1:util"',
    log_outputs: '"3:journald"'
      #log_outputs: '"3:journald 1:file:/tmp/libvirt.log"'

  },
  autiting: {
    #audit_level = 2,
    #audit_logging: 1
  },
  uuid: {
    #host_uuid: '"00000000-0000-0000-0000-000000000000"',
    host_uuid_source: '"smbios"'
  },
  keepalive: {
    #keepalive_interval: 5,
    #keepalive_count: 5,
    #keepalive_required: 1,
    #admin_keepalive_required: 1,
    #admin_keepalive_interval: 5,
    #admin_keepalive_count: 5
  },
  ovs: {
    #timeout: 5
  }
}

virtlogd_cfg: {
  usocket: {
    rw_perms: "0660", # 0666,
    admin_perms: "0600", # 0600
    group: "{{ _libvirt_group }}"
  },
  log: {
    log_level: 3,
    #log_filters: '"1:qemu 1:libvirt 4:object 4:json 4:event 1:util"',
    log_outputs: '"3:journald"'
    #max_clients: 1024,
    #admin_max_clients: 5,
    #max_siz: 2097152,
    #max_backups: 3
  }
}
virtlockd_cfg: {
  usocket: {
    rw_perms: "0660", # 0666,
    admin_perms: "0600" , # 0600
    group: "{{ _libvirt_group }}"
# 0600
  },
  log: {
    log_level: 3,
    log_outputs: '"3:journald"'
    #log_filters='"1:qemu 1:libvirt 4:object 4:json 4:event 1:util"',
    #log_outputs='"3:syslog:virtlockd"',
    #max_clients: 1024,
    #admin_max_clients: 5
  }
}

libvirt_drivers:
  virtqemud_cfg: {
    usocket: {
      ro_perms: "0666", # 0666,
      rw_perms: "0660", # 0666,
      admin_perms: "0600", # 0600
      group: "{{ _libvirt_group }}"
    },
    auth: {
      unix_ro: '"none"', # polkit,
      unix_rw: '"none"', # polkit,
      # access_drivers: '[ "polkit" ]'
    },
    auth_controls: {
      # sasl_allowed_username_list: '["joe@EXAMPLE.COM", "fred@EXAMPLE.COM" ]'
    },
    process_controls: {
      #max_clients: 5000,
      #max_queued_clients: 1000,
      #max_anonymous_clients: 20,
      #min_workers: 5,
      #max_workers: 20,
      #prio_workers: 5,
      #max_client_requests: 5,
      #admin_min_workers: 1,
      #admin_max_workers: 5,
      #admin_max_clients: 5,
      #admin_max_queued_clients: 5,
      #admin_max_client_requests: 5
    },
    log_controls: {
      log_level: 3,
      log_outputs: '"3:journald"'
      #log_filters='"1:qemu 1:libvirt 4:object 4:json 4:event 1:util"',
      #log_outputs='"3:syslog:virtqemud"'
    },
    auditing: {
      #audit_level = 2,
      #audit_logging: 1
    },
    uuid: {
      #host_uuid: '"00000000-0000-0000-0000-000000000000"',
      host_uuid_source: '"smbios"'
    },
    keepalive: {
      #keepalive_interval: 5,
      #keepalive_count: 5,
      #keepalive_required: 1,
      #admin_keepalive_required: 1,
      #admin_keepalive_interval: 5,
      #admin_keepalive_count: 5
    },
    ovs: {
      #timeout: 5
    }
  }
  
  virtinterfaced_cfg: {
    usocket: {
      ro_perms: "0666", # 0666,
      rw_perms: "0660", # 0666,
      admin_perms: "0600" , # 0600
      group: "{{ _libvirt_group }}"
    },
    auth: {
      unix_ro: '"none"', # polkit,
      unix_rw: '"none"', # polkit,
      # access_drivers: '[ "polkit" ]'
    },
    auth_controls: {
      #    sasl_allowed_username_list: '["joe@EXAMPLE.COM", "fred@EXAMPLE.COM" ]'
    },
    process_controls: {
      #max_clients: 5000,
      #max_queued_clients: 1000,
      #max_anonymous_clients: 20,
      #min_workers: 5,
      #max_workers: 20,
      #prio_workers: 5,
      #max_client_requests: 5,
      #admin_min_workers: 1,
      #admin_max_workers: 5,
      #admin_max_clients: 5,
      #admin_max_queued_clients: 5,
      #admin_max_client_requests: 5
    },
    log_controls: {
      log_level: 3,
      log_outputs: '"3:journald"'
      #log_filters='"1:qemu 1:libvirt 4:object 4:json 4:event 1:util"',
      #log_outputs='"3:syslog:virtinterfaced"'
    },
    auditing: {
      #audit_level = 2,
      #audit_logging: 1
    },
    uuid: {
      #host_uuid: '"00000000-0000-0000-0000-000000000000"',
      host_uuid_source: '"smbios"'
    },
    keepalive: {
      #keepalive_interval: 5,
      #keepalive_count: 5,
      #keepalive_required: 1,
      #admin_keepalive_required: 1,
      #admin_keepalive_interval: 5,
      #admin_keepalive_count: 5
    },
    ovs: {
      #timeout: 5
    }
  }
  
  virtnodedevd_cfg: {
    usocket: {
      ro_perms: "0666", # 0666,
      rw_perms: "0660", # 0666,
      admin_perms: "0600" , # 0600
      group: "{{ _libvirt_group }}"
    },
    auth: {
      unix_ro: '"none"', # polkit,
      unix_rw: '"none"', # polkit,
      # access_drivers: '[ "polkit" ]'
    },
    auth_controls: {
      #    sasl_allowed_username_list: '["joe@EXAMPLE.COM", "fred@EXAMPLE.COM" ]'
    },
    process_controls: {
      #max_clients: 5000,
      #max_queued_clients: 1000,
      #max_anonymous_clients: 20,
      #min_workers: 5,
      #max_workers: 20,
      #prio_workers: 5,
      #max_client_requests: 5,
      #admin_min_workers: 1,
      #admin_max_workers: 5,
      #admin_max_clients: 5,
      #admin_max_queued_clients: 5,
      #admin_max_client_requests: 5
    },
    log_controls: {
      log_level: 3,
      log_outputs: '"3:journald"'
      #log_filters='"1:qemu 1:libvirt 4:object 4:json 4:event 1:util"',
      #log_outputs='"3:syslog:virtnodedevd"'
    },
    auditing: {
      #audit_level = 2,
      #audit_logging: 1
    },
    uuid: {
      #host_uuid: '"00000000-0000-0000-0000-000000000000"',
      host_uuid_source: '"smbios"'
    },
    keepalive: {
      #keepalive_interval: 5,
      #keepalive_count: 5,
      #keepalive_required: 1,
      #admin_keepalive_required: 1,
      #admin_keepalive_interval: 5,
      #admin_keepalive_count: 5
    },
    ovs: {
      #timeout: 5
    }
  }
  
  virtstoraged_cfg: {
    usocket: {
      ro_perms: "0666", # 0666,
      rw_perms: "0660", # 0666,
      admin_perms: "0600" , # 0600
      group: "{{ _libvirt_group }}"
    },
    auth: {
      unix_ro: '"none"', # polkit,
      unix_rw: '"none"', # polkit,
      # access_drivers: '[ "polkit" ]'
    },
    auth_controls: {
      #    sasl_allowed_username_list: '["joe@EXAMPLE.COM", "fred@EXAMPLE.COM" ]'
    },
    process_controls: {
      #max_clients: 5000,
      #max_queued_clients: 1000,
      #max_anonymous_clients: 20,
      #min_workers: 5,
      #max_workers: 20,
      #prio_workers: 5,
      #max_client_requests: 5,
      #admin_min_workers: 1,
      #admin_max_workers: 5,
      #admin_max_clients: 5,
      #admin_max_queued_clients: 5,
      #admin_max_client_requests: 5
    },
    log_controls: {
      log_level: 3,
      log_outputs: '"3:journald"'
      #log_filters='"1:qemu 1:libvirt 4:object 4:json 4:event 1:util"',
      #log_outputs='"3:syslog:virtstoraged"'
    },
    auditing: {
      #audit_level = 2,
      #audit_logging: 1
    },
    uuid: {
      #host_uuid: '"00000000-0000-0000-0000-000000000000"',
      host_uuid_source: '"smbios"'
    },
    keepalive: {
      #keepalive_interval: 5,
      #keepalive_count: 5,
      #keepalive_required: 1,
      #admin_keepalive_required: 1,
      #admin_keepalive_interval: 5,
      #admin_keepalive_count: 5
    },
    ovs: {
      #timeout: 5
    }
  }
  
  virtnetworkd_cfg: {
    usocket: {
      ro_perms: "0666", # 0666,
      rw_perms: "0660", # 0666,
      admin_perms: "0600" , # 0600
      group: "{{ _libvirt_group }}"
    },
    auth: {
      unix_ro: '"none"', # polkit,
      unix_rw: '"none"', # polkit,
      # access_drivers: '[ "polkit" ]'
    },
    auth_controls: {
      #    sasl_allowed_username_list: '["joe@EXAMPLE.COM", "fred@EXAMPLE.COM" ]'
    },
    process_controls: {
      #max_clients: 5000,
      #max_queued_clients: 1000,
      #max_anonymous_clients: 20,
      #min_workers: 5,
      #max_workers: 20,
      #prio_workers: 5,
      #max_client_requests: 5,
      #admin_min_workers: 1,
      #admin_max_workers: 5,
      #admin_max_clients: 5,
      #admin_max_queued_clients: 5,
      #admin_max_client_requests: 5
    },
    log_controls: {
      log_level: 3,
      log_outputs: '"3:journald"'
      #log_filters='"1:qemu 1:libvirt 4:object 4:json 4:event 1:util"',
      #log_outputs='"3:syslog:virtnetwordd"'
    },
    auditing: {
      #audit_level = 2,
      #audit_logging: 1
    },
    uuid: {
      #host_uuid: '"00000000-0000-0000-0000-000000000000"',
      host_uuid_source: '"smbios"'
    },
    keepalive: {
      #keepalive_interval: 5,
      #keepalive_count: 5,
      #keepalive_required: 1,
      #admin_keepalive_required: 1,
      #admin_keepalive_interval: 5,
      #admin_keepalive_count: 5
    },
    ovs: {
      #timeout: 5
    }
  }
  
  virtnwfilterd_cfg: {
    usocket: {
      ro_perms: "0666", # 0666,
      rw_perms: "0660", # 0666,
      admin_perms: "0600" , # 0600
      group: "{{ _libvirt_group }}"
    },
    auth: {
      unix_ro: '"none"', # polkit,
      unix_rw: '"none"', # polkit,
      # access_drivers: '[ "polkit" ]'
    },
    auth_controls: {
      #    sasl_allowed_username_list: '["joe@EXAMPLE.COM", "fred@EXAMPLE.COM" ]'
    },
    process_controls: {
      #max_clients: 5000,
      #max_queued_clients: 1000,
      #max_anonymous_clients: 20,
      #min_workers: 5,
      #max_workers: 20,
      #prio_workers: 5,
      #max_client_requests: 5,
      #admin_min_workers: 1,
      #admin_max_workers: 5,
      #admin_max_clients: 5,
      #admin_max_queued_clients: 5,
      #admin_max_client_requests: 5
    },
    log_controls: {
      log_level: 3,
      log_outputs: '"3:journald"'
      #log_filters='"1:qemu 1:libvirt 4:object 4:json 4:event 1:util"',
      #log_outputs='"3:syslog:virtnwfilterd"'
    },
    auditing: {
      #audit_level = 2,
      #audit_logging: 1
    },
    uuid: {
      #host_uuid: '"00000000-0000-0000-0000-000000000000"',
      host_uuid_source: '"smbios"'
    },
    keepalive: {
      #keepalive_interval: 5,
      #keepalive_count: 5,
      #keepalive_required: 1,
      #admin_keepalive_required: 1,
      #admin_keepalive_interval: 5,
      #admin_keepalive_count: 5
    },
    ovs: {
      #timeout: 5
    }
  }
  
  virtsecretd_cfg: {
    usocket: {
      ro_perms: "0666", # 0666,
      rw_perms: "0660", # 0666,
      admin_perms: "0600" , # 0600
      group: "{{ _libvirt_group }}"
    },
    auth: {
      unix_ro: '"none"', # polkit,
      unix_rw: '"none"', # polkit,
      # access_drivers: '[ "polkit" ]'
    },
    auth_controls: {
      #    sasl_allowed_username_list: '["joe@EXAMPLE.COM", "fred@EXAMPLE.COM" ]'
    },
    process_controls: {
      #max_clients: 5000,
      #max_queued_clients: 1000,
      #max_anonymous_clients: 20,
      #min_workers: 5,
      #max_workers: 20,
      #prio_workers: 5,
      #max_client_requests: 5,
      #admin_min_workers: 1,
      #admin_max_workers: 5,
      #admin_max_clients: 5,
      #admin_max_queued_clients: 5,
      #admin_max_client_requests: 5
    },
    log_controls: {
      log_level: 3,
      log_outputs: '"3:journald"'
      #log_filters='"1:qemu 1:libvirt 4:object 4:json 4:event 1:util"',
      #log_outputs='"3:syslog:virtsecretd"'
    },
    auditing: {
      #audit_level = 2,
      #audit_logging: 1
    },
    uuid: {
      #host_uuid: '"00000000-0000-0000-0000-000000000000"',
      host_uuid_source: '"smbios"'
    },
    keepalive: {
      #keepalive_interval: 5,
      #keepalive_count: 5,
      #keepalive_required: 1,
      #admin_keepalive_required: 1,
      #admin_keepalive_interval: 5,
      #admin_keepalive_count: 5
    },
    ovs: {
      #timeout: 5
    }
  }
  
