domain_real_computers: {
    "fenris": {
        "name":             "fenris",
        "dns_hostname":     "fenris.haas.local",
        "description":      "mssql",
        "path":             "OU=Servers,OU=Cybernetics,OU=Asa,DC=haas,DC=local",            
        "delegates"       : [], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
        "delegation_type" : false, # "KCD", "KUD", false
        "constrained"     : [], # KCD / SPN list / msDS-AllowedToDelegateTo
        "proto_transition": false,  # KCD default false
        "sensitive"       : false
    },
    "architect": {
        "name":             "architect",
        "dns_hostname":     "architect.haas.local",
        "description":      "ws",
        "path":             "OU=Workstations,OU=Cybernetics,OU=Asa,DC=haas,DC=local",            
        "delegates"       : [], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
        "delegation_type" : false, # "KCD", "KUD", false
        "constrained"     : [], # KCD / SPN list / msDS-AllowedToDelegateTo
        "proto_transition": false,  # KCD default false
        "sensitive"       : false
    }
}

domain_fake_computers: {}
