domain_gmsa : {
  "ichi": {
    "gMSA_Name" : "ichi",
    "gMSA_FQDN" : "ichi_v2.haas.local",
    "gMSA_SPNs" : ["MSSQLSvc/fenris.haas.local:1433","MSSQLSvc/fenris.haas.local"],
    "gMSA_Groups" : ["L_GMSA_ICHI"], # computer account must be in the group not in nested groups
    "path"            : "CN=Managed Service Accounts,DC=haas,DC=local",            
    "delegates"       : [], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
    "delegation_type" : false, # "KCD", "KUD", false
    "constrained"     : [], # KCD / SPN list / msDS-AllowedToDelegateTo
    "proto_transition": true,  # KCD default false
    "sensitive"       : false,
    "ADAC": {
        "AllowReversiblePasswordEncryption": false,
        "CannotChangePassword":              false,
        "PasswordNeverExpires":              false,
        "PasswordNotRequired":               false,
        "AccountNotDelegated":               false,
        "DoesNotRequirePreAuth":             false
    }  
  }
  
}