domain_service_accounts: {}

domain_users_regular: {
    "jubeaz" : {
        "firstname"       : "Mr.",
        "surname"         : "Jubeaz",
        "password"        : "jubeaz", 
        "city"            : "-",
        "description"     : "",
        "groups"          : ["Domain Admins"], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local"
    }
}