---
- name: Set CA base params
  set_fact:
    _ca_csr_dir: "{{ hostvars[_ca_name].ca_base_dir }}/{{ hostvars[_ca_name].ca_csr_dir }}/{{ _ca_template_name }}"
    _ca_template_model: "{{ hostvars[_ca_name]['ca_templates'][_ca_template_name] }}"
    _ca_templates_params: "{{ hostvars[_ca_name].ca_templates_params }}"

- name: Set CA template parameters
  set_fact:
    _ca_template_params: "{{ _ca_templates_params[_ca_template_model] }}"

