Vagrant.configure("2") do |config|

# Uncomment this depending on the provider you want to use
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
#ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_desktop'

boxes = [
  # windows 10
  #{ :name => "blue",  :ip => "192.168.56.13", :box => "StefanScherer/windows_10", :box_version => "2021.12.09", :os => "windows"},
  #{ :name => "blue",  :ip => "192.168.56.13", :box => "StefanScherer/windows_11", :box_version => "2021.12.09", :os => "windows"},
  #{ :name => "blue",  :ip => "192.168.56.13", :box => "StefanScherer/windows_2019", :box_version => "2021.05.15", :os => "windows"},
  { :name => "srv01",  :ip => "192.168.56.11", :box => "gusztavvargadr/windows-server", :box_version => "2102.0.2310", :os => "windows", :ram => 4096, :cpu => 2},
  #{ :name => "srv01",  :ip => "192.168.56.11", :box => "gusztavvargadr/windows-server-core", :box_version => "2102.0.2310", :os => "windows", :ram => 2048, :cpu => 2},
  { :name => "srv02",  :ip => "192.168.56.31", :box => "gusztavvargadr/windows-server", :box_version => "2102.0.2310", :os => "windows", :ram => 4096, :cpu => 2},
  #{ :name => "srv02",  :ip => "192.168.56.31", :box => "gusztavvargadr/windows-server-core", :box_version => "2102.0.2310", :os => "windows", :ram => 2048, :cpu => 2},
  #{ :name => "dc01",  :ip => "192.168.56.10", :box => "gusztavvargadr/windows-server", :box_version => "2102.0.2310", :os => "windows", :ram => 4096, :cpu => 2},
  #{ :name => "dc01",  :ip => "192.168.56.10", :box => "gusztavvargadr/windows-server-core", :box_version => "2102.0.2310", :os => "windows", :ram => 2048, :cpu => 2},
  #{ :name => "dc02",  :ip => "192.168.56.20", :box => "gusztavvargadr/windows-server", :box_version => "2102.0.2310", :os => "windows", :ram => 4096, :cpu => 2},
  #{ :name => "dc02",  :ip => "192.168.56.20", :box => "gusztavvargadr/windows-server-core", :box_version => "2102.0.2310", :os => "windows", :ram => 2048, :cpu => 2},
  { :name => "dc03",  :ip => "192.168.56.30", :box => "gusztavvargadr/windows-server", :box_version => "2102.0.2310", :os => "windows", :ram => 4096, :cpu => 2},
  #{ :name => "dc03",  :ip => "192.168.56.30", :box => "gusztavvargadr/windows-server-core", :box_version => "2102.0.2310", :os => "windows", :ram => 2048, :cpu => 2}
]


  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
  end

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "4000"
    v.vmx["numvcpus"] = "2"
  end

  # disable rdp forwarded port inherited from StefanScherer box
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true, disabled: true

  # no autoupdate if vagrant-vbguest is installed
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 10
  config.winrm.transport = "plaintext"
  config.winrm.basic_auth_only = true

  boxes.each do |box|
    config.vm.define box[:name] do |target|
      # BOX
      target.vm.provider "virtualbox" do |v|
        v.memory = box[:ram]
        v.name = box[:name]
      end

      target.vm.box_download_insecure = box[:box]
      target.vm.box = box[:box]
      if box.has_key?(:box_version)
        target.vm.box_version = box[:box_version]
      end

      # issues/49
      target.vm.synced_folder '.', '/vagrant', disabled: true
      target.vm.synced_folder 'shared/', '/shared', disabled: true

      # IP
      target.vm.network :private_network, ip: box[:ip]
      #target.vm.network :public_network, bridge: 'br0', ip: box[:ip]
      #config.vm.provision "shell",
      #  run: "always",
      #  inline: "route add default gw 192.168.2.1"

      # OS specific
      if box[:os] == "windows"
        target.vm.guest = :windows
        target.vm.communicator = "winrm"
        target.vm.provision :shell, :path => "../scripts/Install-WMF3Hotfix.ps1", privileged: false
        target.vm.provision :shell, :path => "../scripts/ConfigureRemotingForAnsible.ps1", privileged: false

        # fix ip for vmware
        if ENV['VAGRANT_DEFAULT_PROVIDER'] == "vmware_desktop"
          target.vm.provision :shell, :path => "../scripts/fix_ip.ps1", privileged: false, args: box[:ip]
        end

      else
        target.vm.communicator = "ssh"
      end

      if box.has_key?(:forwarded_port)
        # forwarded port explicit
        box[:forwarded_port] do |forwarded_port|
          target.vm.network :forwarded_port, guest: forwarded_port[:guest], host: forwarded_port[:host], host_ip: "127.0.0.1", id: forwarded_port[:id]
        end
      end

    end
  end
end
